### PR TITLE
Solving #28 and #33

### PR DESCRIPTION
**Pull request by oltdaniel**

### CODE REVIEW

**Comment by davidlazar** [comment]
Thanks for the submission. Could you separate these out into two separate commits?

I'm thinking that `/cancelfriend` can be merged into `/delfriend`, to avoid an extra command.

For aliases, I'm thinking the `Command` struct should have an extra `Aliases` field. This way the help info doesn't need to be duplicated across commands.

**Comment by oltdaniel** [comment]
Ok will make the changes tomorrow.

**Comment by oltdaniel** [comment]
@davidlazar The command alias code will be in a new pull request.

**Comment by davidlazar** [comment]
Looking better. Could you squash these into two commits (one for each issue) and use the same commit message format as the rest of the commits in the repo? The commit messages should look like: `cmd/vuvuzela-client: ...`

**Comment by oltdaniel** [comment]
@davidlazar So I will close this now and open a new clean pull request if you want?

**Pull request closed without merging**
